### ISSUE TITLE
WebUI doesn't present the registration screen on first start

### ISSUE THREAD

**Issue by obedox** [ConcreteLlama/digital-foundry-downloader#1]
On initial launch of the WebUI I'm presented with a login screen, but I haven't added an account yet.  Looking at the source it seems like a registration page is supposed to launch on the first setup but that doesn't seem to be happening.

**Comment by ConcreteLlama** [comment]
Just tried a fresh pull and the register screen is presented to me. I can replicate your issue if there is no communication between the frontend and the backend; maybe I should add something into the UI to make it clearer when the connection fails.

Based on what you've said I'm wondering if you're running the UI on its own without having the backend up, which won't work. What steps did you take to get it built and running?

The quickest and easiest way to get it running is to go into the root directory (not df-downloader-ui) then run:

`npm run build`

which gets all deps/builds everything then

`npm run start`

which runs the backend, hosting the built web UI

**Comment by obedox** [comment]
I went the Docker route and built an image using the following command from the README.md
`docker build . -t  concretellama/df-downloader-node`

Then started it with the following command
`docker run -d \
  --env WORK_DIR="//working_dir" \
  --env DESTINATION_DIR="//destination_dir" \
  --env CONFIG_DIR="//config" \
  --env DB_DIR="//db" \
  --env PUBLIC_ADDRESS=http://127.0.0.1:44556 \
  -v <localpath>:/working_dir \
  -v <localpath>:/destination_dir \
  -v <localpath>:/config \
  -v <localpath>:/db \
  -p 44556:44556 \
  --name df-downloader \
  concretellama/df-downloader-node`

I saw the file `users.yaml` was created in the config dir with the following: `users: []` 
But still getting the login screen, no registration.

I was able to manually modify the `config.yaml` with my SessionID and it seems like the service is working, it created the `db.json` and populated it with data.  I can see it's fetching metadata and updating things looking at the logs.

Thanks for the quick response, apologies I should have provided more details on my setup in the OP.

**Comment by ConcreteLlama** [comment]
Definitely sounds like the UI is failing to connect to the backend. Can you check your browser network logs?

Also how are you trying to access the web UI (as in what address?). If the configured public address doesn't match the address you're accessing it with, you'll get CORS errors and API requests will fail. But if you're running this locally and accessing with 

`http://127.0.0.1:44556`

then it should work and I'm not quite sure what the issue is yet.

**Comment by obedox** [comment]
Ah you're right I had the PUBLIC_ADDRESS variable set incorrectly.  I set it to be the IP address of the host and it's working now.

Thanks for the help!  Great tool! :)
