### ISSUE TITLE
typo in dockerhub instructions

### ISSUE THREAD

**Issue by cubismod** [ConcreteLlama/digital-foundry-downloader#2]
Just wanted to let you know that the `docker run` command that you have at https://hub.docker.com/r/concretellama/digital-foundry-downloader has a typo for the image name:

`concretellama/df-downloader-node:latest` should be `concretellama/digital-foundry-downloader-node:latest`.

Hopefully will save people setting up the docker image in the future. Thanks for making this!

**Comment by ConcreteLlama** [comment]
Thanks for bringing this to my attention, I did not notice this! I think your issue comment has a typo and it should in fact be `concretellama/digital-foundry-downloader` not `concretellama/digital-foundry-downloader-node` so I have updated all documentation to use `concretellama/digital-foundry-downloader`. If by some weird voodoo magic that's incorrect please reopen the issue!
