### ISSUE TITLE
Trouble installing standalone

### ISSUE THREAD

**Issue by Jordan-Ch** [ConcreteLlama/digital-foundry-downloader#3]
Trying to install the standalone. 
I grabbed node.js then downloaded the project from this github. 
Unzipped, opened the root directly but the command "npm run build" errors out. 

Having trouble figuring out what I am missing. 

`C:\Programs\digital-foundry-downloader-main>npm run build

> digital-foundry-downloader@2.2.5 build
> cd df-downloader-common && npm i && npm run build && cd ../df-downloader-ui && npm run full-build && cd ../df-downloader-service && npm run full-build && npm run get-ui

up to date, audited 98 packages in 745ms

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> df-downloader-common@1.0.0 build
> mkdirp dist && shx cp package.json dist && cd dist && yalc publish --private --push

Running preyalcpublish script: tsc

> df-downloader-common@1.0.0 preyalcpublish
> tsc

df-downloader-common@1.0.0 published in store.
npm error Missing script: "full-build"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: C:\Users\Jorda\AppData\Local\npm-cache\_logs\2024-08-30T05_26_18_150Z-debug-0.log`

**Comment by ConcreteLlama** [comment]
Looks like I accidentally removed the full-build script from the UI code's package.json when switching the ui to use vite. I have pushed a new update to main; can you pull and try again?

**Comment by Jordan-Ch** [comment]
Hey thanks!
Unfortunately I am still getting another error when building this haha. 
Maybe there is some type of user error on my part, Going to try and find our what "yalc" is and why my pc doesn't recognize it. 

```
PS C:\Programs\DF_Downloader> npm run build

> digital-foundry-downloader@2.2.5 build
> cd df-downloader-common && npm i && npm run build && cd ../df-downloader-ui && npm run full-build && cd ../df-downloader-service && npm run full-build && npm run get-ui


up to date, audited 98 packages in 711ms

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> df-downloader-common@1.0.0 build
> mkdirp dist && shx cp package.json dist && cd dist && yalc publish --private --push

Running preyalcpublish script: tsc

> df-downloader-common@1.0.0 preyalcpublish
> tsc

df-downloader-common@1.0.0 published in store.

> df-downloader-ui@0.0.0 full-build
> npm i && npm run add-common && npm run build


changed 1 package, and audited 375 packages in 976ms

98 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> df-downloader-ui@0.0.0 add-common
> yalc add df-downloader-common

'yalc' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Programs\DF_Downloader>
```

**Comment by Jordan-Ch** [comment]
I figured it out, I guess yalc must not be included with the current lts version of nodejs. 
I ran "npm install -g yalc"

Then was able to build without issues. 
Maybe this archived issue will help another shlub like me down the road :)

**Comment by ConcreteLlama** [comment]
To be fair yalc isn't a very well known tool and I should either have included it in the instructions or added it as a dep and run it through npm. I'll see if I can do something about this another time. Let me know if you hit any other issues, and feel free to message me on discord if you need help

**Comment by Jordan-Ch** [comment]
Hey I have another question about how to use this. 
I when you start the service and go to the web ui, it prompts you to make a user but never prompts for the "sessionid" thats needed for authentication. 

I dug around and found root\df-downloader-service\config\config.yaml

Tried to add the sessionid in there assuming that's what was needed, but I am still getting "Unauthorized". I removed the comment #s in the first 3 lines. So it looks like:

```
digitalFoundry:
   # Digital Foundry sessionid cookie
   sessionId: "my session ID is here"
```
   
I assume I am missing a step.

**Comment by ConcreteLlama** [comment]
Hey @Jordan-Ch , I'm not near my computer right now so can't verify this but it's possibly a CORS issue. The address you use to access the web UI must match the configured allowed origins. By default this would be http://127.0.0.1:44556 (note that this is different to http://localhost:44556). If you're putting it behind a DNS you need to ensure the allowed origins include the DNS name you're accessing the web UI with.

Also, if you're running the web UI separate to the service (which you don't need to do unless you're planning on making changes) you'd need the web UI address as an origin in your config.

What does your config file look like (obviously redact anything confidential)? And what address are you using to access the web UI?

**Comment by Jordan-Ch** [comment]
That was exactly it. 
I was accessing the web UI via http://localhost:44556/

Thank you!
